version: "3"

networks:
  kong-network:
    driver: bridge

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    networks:
      - kong-network
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    volumes:
      - ./kong_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      retries: 5
      timeout: 5s

  kong-migrations:
    image: kong
    depends_on:
      - kong-database
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    networks:
      - kong-network

  kong:
    image: kong
    depends_on:
      - kong-database
      - kong-migrations
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PORTAL_GUI_HOST: http://localhost:8002
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    networks:
      - kong-network

  importer-module:
    platform: linux/x86_64
    container_name: importer-module
    image: getnuvo/importer:latest
    ports:
      - "3000:3000"
    env_file:
      - ./importer-module.docker.env
    links:
      - mongo
      - mapping-module
    networks:
      - kong-network
    # healthcheck:
    #   test:
    #     ["CMD", "curl", "-f", "http://localhost:3000/sdk/v1/auth/health"]
    #   interval: 10s
    #   retries: 5
    #   timeout: 5s

  mapping-module:
    platform: linux/x86_64
    container_name: mapping-module
    image: 142674448920.dkr.ecr.eu-central-1.amazonaws.com/nuvo-mapping-module:staging
    env_file:
      - ./mapping-module.docker.env
    ports:
      - "3001:8000"
    networks:
      - kong-network

  mongo:
    container_name: my-mongo-db
    image: mongo:latest
    volumes:
      - ./db_backup:/data/db
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nuvo
      - MONGO_INITDB_ROOT_PASSWORD=nuvo
    networks:
      - kong-network
