apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --chart -o zzz
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: importer-module
  name: importer-module
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: importer-module
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --chart -o zzz
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: importer-module
    spec:
      containers:
        - env:
            - name: IMPORTER_PORT
              valueFrom:
                configMapKeyRef:
                  key: IMPORTER_PORT
                  name: importer-module-docker-env
            - name: IMPORTER_DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: IMPORTER_DB_HOST
                  name: importer-module-docker-env
            - name: IMPORTER_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: IMPORTER_DB_NAME
                  name: importer-module-docker-env
            - name: IMPORTER_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: IMPORTER_DB_PASSWORD
                  name: importer-module-docker-env
            - name: IMPORTER_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: IMPORTER_DB_USERNAME
                  name: importer-module-docker-env
            - name: IMPORTER_PORT
              valueFrom:
                configMapKeyRef:
                  key: IMPORTER_PORT
                  name: importer-module-docker-env
            - name: IMPORTER_LICENSE_KEY
              valueFrom:
                configMapKeyRef:
                  key: IMPORTER_LICENSE_KEY
                  name: importer-module-docker-env
          image: "{{ .Values.nuvo.image.repository }}:{{ .Values.nuvo.image.tag }}"
          name: importer-module
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
        - name: my-dockerhub-secret
