apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --chart -o helm-chart
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  ports:
    - name: '27018'
      port: 27018
      targetPort: 27017
  selector:
    io.kompose.service: mongo
