apiVersion: v2
name: ingestro-importer
description: Helm chart that deploys the Ingestro Importer, Mapping, AI service, and MongoDB stack.
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://ingestro.com
sources:
  - https://github.com/getnuvo/importer-onpremise
keywords:
  - ingestro
  - importer
  - mapping
  - ai
  - mongo
maintainers:
  - name: ingestro
    email: support@ingestro.com
