apiVersion: v1
data:
  MAPPING_BE_URL: http://importer-module.ingress-nginx.svc.cluster.local:3000
  MAPPING_PORT: "8000"
  
  MAPPING_LLM_PROVIDER: AZURE
  MAPPING_LLM_TEMPERATURE: "0.7"

  MAPPING_AWS_BEDROCK_ACCESS_KEY_ID: your-access-key-id
  MAPPING_AWS_BEDROCK_MODEL_ID: name
  MAPPING_AWS_BEDROCK_REGION: region
  MAPPING_AWS_BEDROCK_SECRET_ACCESS_KEY: your-secret-key

  MAPPING_AZURE_OPENAI_API_KEY: key
  MAPPING_AZURE_OPENAI_API_VERSION: version
  MAPPING_AZURE_OPENAI_DEPLOYMENT_NAME: name
  MAPPING_AZURE_OPENAI_ENDPOINT: https://your-endpoint.openai.azure.com
  
  MAPPING_LANGFUSE_HOST: https://langfuse.example.com
  MAPPING_LANGFUSE_PUBLIC_KEY: key
  MAPPING_LANGFUSE_SECRET_KEY: key
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: mapping-module-mapping-module-docker-env
  name: mapping-module-docker-env
