apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yml --chart -o mapping-module-chart
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: mapping-module
  name: mapping-module
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mapping-module
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.dev.yml --chart -o mapping-module-chart
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: mapping-module
    spec:
      containers:
        - env:
            - name: MAPPING_AWS_BEDROCK_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: MAPPING_AWS_BEDROCK_ACCESS_KEY_ID
                  name: mapping-module-docker-env
            - name: MAPPING_AWS_BEDROCK_MODEL_ID
              valueFrom:
                configMapKeyRef:
                  key: MAPPING_AWS_BEDROCK_MODEL_ID
                  name: mapping-module-docker-env
            - name: MAPPING_AWS_BEDROCK_REGION
              valueFrom:
                configMapKeyRef:
                  key: MAPPING_AWS_BEDROCK_REGION
                  name: mapping-module-docker-env
            - name: MAPPING_AWS_BEDROCK_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: MAPPING_AWS_BEDROCK_SECRET_ACCESS_KEY
                  name: mapping-module-docker-env
            - name: MAPPING_AZURE_OPENAI_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: MAPPING_AZURE_OPENAI_API_KEY
                  name: mapping-module-docker-env
            - name: MAPPING_AZURE_OPENAI_API_VERSION
              valueFrom:
                configMapKeyRef:
                  key: MAPPING_AZURE_OPENAI_API_VERSION
                  name: mapping-module-docker-env
            - name: MAPPING_AZURE_OPENAI_DEPLOYMENT_NAME
              valueFrom:
                configMapKeyRef:
                  key: MAPPING_AZURE_OPENAI_DEPLOYMENT_NAME
                  name: mapping-module-docker-env
            - name: MAPPING_AZURE_OPENAI_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: MAPPING_AZURE_OPENAI_ENDPOINT
                  name: mapping-module-docker-env
            - name: MAPPING_BE_URL
              valueFrom:
                configMapKeyRef:
                  key: MAPPING_BE_URL
                  name: mapping-module-docker-env
            - name: MAPPING_LANGFUSE_HOST
              valueFrom:
                configMapKeyRef:
                  key: MAPPING_LANGFUSE_HOST
                  name: mapping-module-docker-env
            - name: MAPPING_LANGFUSE_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  key: MAPPING_LANGFUSE_PUBLIC_KEY
                  name: mapping-module-docker-env
            - name: MAPPING_LANGFUSE_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: MAPPING_LANGFUSE_SECRET_KEY
                  name: mapping-module-docker-env
            - name: MAPPING_LLM_PROVIDER
              valueFrom:
                configMapKeyRef:
                  key: MAPPING_LLM_PROVIDER
                  name: mapping-module-docker-env
            - name: MAPPING_LLM_TEMPERATURE
              valueFrom:
                configMapKeyRef:
                  key: MAPPING_LLM_TEMPERATURE
                  name: mapping-module-docker-env
            - name: MAPPING_PORT
              valueFrom:
                configMapKeyRef:
                  key: MAPPING_PORT
                  name: mapping-module-docker-env
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          name: mapping-module
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
        - name: my-dockerhub-secret
