apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-nginx-ingress
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /sdk/mapping/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: mapping-module
                port:
                  number: 3001
          - path: /ai-service/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ai-service-module
                port:
                  number: 3002
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: importer-module
                port:
                  number: 3000
