{{- if .Values.aiService.enabled }}
{{- $root := . }}
{{- $component := "aiService" }}
{{- $values := $root.Values.aiService | default dict }}
{{- $source := default (dict) $values.secrets }}
{{- $secretData := dict }}
{{- range $key, $val := $source }}
  {{- if ne (printf "%v" $val) "" }}
    {{- $_ := set $secretData $key (printf "%v" $val) }}
  {{- end }}
{{- end }}
{{- $globalLicense := default "" $root.Values.global.licenseKey }}
{{- if and (ne (printf "%v" $globalLicense) "") (not (hasKey $secretData "SERVICE_LICENSE_KEY")) }}
  {{- $_ := set $secretData "SERVICE_LICENSE_KEY" (printf "%v" $globalLicense) }}
{{- end }}
{{- $defaultSecretName := include "ingestro-importer.componentFullname" (dict "root" $root "component" $component "suffix" "secret") }}
{{- $secretRef := $values.secretRef | default dict }}
{{- $existingSecret := default "" $secretRef.existingSecret }}
{{- $external := $values.externalSecret | default dict }}
{{- $externalEnabled := default false $external.enabled }}
{{- $target := $external.target | default dict }}
{{- $targetName := default $defaultSecretName $target.name }}
{{- $externalName := default (printf "%s-external" $targetName) $external.name }}
{{- if $existingSecret }}
{{- else if $externalEnabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $externalName | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "ingestro-importer.componentLabels" (dict "root" $root "component" $component) | nindent 4 }}
spec:
  refreshInterval: {{ default "1h" $external.refreshInterval | quote }}
  secretStoreRef:
    name: {{ required (printf "aiService.externalSecret.secretStoreRef.name is required when aiService.externalSecret.enabled=true") $external.secretStoreRef.name }}
    kind: {{ default "ClusterSecretStore" $external.secretStoreRef.kind }}
  target:
    name: {{ $targetName }}
    {{- with $target.creationPolicy }}
    creationPolicy: {{ . | quote }}
    {{- end }}
    {{- with $target.deletionPolicy }}
    deletionPolicy: {{ . | quote }}
    {{- end }}
    template:
      type: Opaque
  {{- if $external.data }}
  data:
{{ toYaml $external.data | indent 4 }}
  {{- end }}
  {{- if $external.dataFrom }}
  dataFrom:
{{ toYaml $external.dataFrom | indent 4 }}
  {{- end }}
{{- else if gt (len $secretData) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $defaultSecretName }}
  labels:
    {{- include "ingestro-importer.componentLabels" (dict "root" $root "component" $component) | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := $secretData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}