{{- $root := . -}}
{{- $creds := $root.Values.global.imageCredentials | default dict -}}
{{- $external := $creds.externalSecret | default dict -}}
{{- $externalEnabled := default false $external.enabled -}}
{{- $target := $external.target | default dict -}}
{{- $defaultSecretName := include "ingestro-importer.imagePullSecretName" $root -}}
{{- $targetName := default $defaultSecretName $target.name -}}
{{- $externalName := default (printf "%s-external" $targetName) $external.name -}}
{{- if $externalEnabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $externalName | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "ingestro-importer.commonLabels" $root | nindent 4 }}
spec:
  refreshInterval: {{ default "1h" $external.refreshInterval | quote }}
  secretStoreRef:
    name: {{ required (printf "global.imageCredentials.externalSecret.secretStoreRef.name is required when global.imageCredentials.externalSecret.enabled=true") $external.secretStoreRef.name }}
    kind: {{ default "ClusterSecretStore" $external.secretStoreRef.kind }}
  target:
    name: {{ $targetName }}
    {{- with $target.creationPolicy }}
    creationPolicy: {{ . | quote }}
    {{- end }}
    {{- with $target.deletionPolicy }}
    deletionPolicy: {{ . | quote }}
    {{- end }}
    template:
      type: kubernetes.io/dockerconfigjson
  {{- if $external.data }}
  data:
{{ toYaml $external.data | indent 4 }}
  {{- end }}
  {{- if $external.dataFrom }}
  dataFrom:
{{ toYaml $external.dataFrom | indent 4 }}
  {{- end }}
{{- else if and $creds.create ($creds.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $defaultSecretName }}
  labels:
    {{- include "ingestro-importer.commonLabels" $root | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ default "https://index.docker.io/v1/" $creds.registry }}": {
          "username": "{{ $creds.username }}",
          "password": "{{ $creds.password }}",
          "email": "{{ default "" $creds.email }}",
          "auth": "{{ printf "%s:%s" $creds.username $creds.password | b64enc }}"
        }
      }
    }
{{- end }}