{{- if and .Values.global.imageCredentials.create (.Values.global.imageCredentials.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ingestro-importer.imagePullSecretName" . }}
  labels:
    {{- include "ingestro-importer.commonLabels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ default "https://index.docker.io/v1/" .Values.global.imageCredentials.registry }}": {
          "username": "{{ .Values.global.imageCredentials.username }}",
          "password": "{{ .Values.global.imageCredentials.password }}",
          "email": "{{ default "" .Values.global.imageCredentials.email }}",
          "auth": "{{ printf "%s:%s" .Values.global.imageCredentials.username .Values.global.imageCredentials.password | b64enc }}"
        }
      }
    }
{{- end }}

