{{- if .Values.importer.enabled }}
{{- $root := . }}
{{- $component := "importer" }}
{{- $source := default (dict) $root.Values.importer.secrets }}
{{- $secretData := dict }}
{{- range $key, $val := $source }}
  {{- if ne (printf "%v" $val) "" }}
    {{- $_ := set $secretData $key (printf "%v" $val) }}
  {{- end }}
{{- end }}
{{- $globalLicense := default "" $root.Values.global.licenseKey }}
{{- if and (ne (printf "%v" $globalLicense) "") (not (hasKey $secretData "IMPORTER_LICENSE_KEY")) }}
  {{- $_ := set $secretData "IMPORTER_LICENSE_KEY" (printf "%v" $globalLicense) }}
{{- end }}
{{- if gt (len $secretData) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ingestro-importer.componentFullname" (dict "root" $root "component" $component "suffix" "secret") }}
  labels:
    {{- include "ingestro-importer.componentLabels" (dict "root" $root "component" $component) | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := $secretData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}

